let str1 = "Hello";
let str2 = "World";
let str3 = "JavaScript";
let str4 = "Variables";
let str5 = "Different";
let str6 = "Types";
let str7 = "Data";
let str8 = "String";
let str9 = "Number";
let str10 = "Boolean";
let num1 = 5;
let num2 = 15.75;
let num3 = -45;
let num4 = 100;
let num5 = 89;
let num6 = 2.718;
let num7 = 500;
let num8 = 2023;
let num9 = -1.414;
let num10 = 3.14159;
let bool1 = false;
let bool2 = true;
let bool3 = false;
let bool4 = true;
let bool5 = false;
let bool6 = true;
let bool7 = false;
let bool8 = true;
let bool9 = false;
let bool10 = true;
let arr1 = [4, 5, 6];
let arr2 = ["Mango", "Apple", "Grape"];
let arr3 = [false, true, false];
let arr4 = [7.7, 8.8, 9.9];
let arr5 = ["Black", "White", "Gray"];
let obj1 = {name: "Mohammed", age: 30};
let obj2 = {city: "Cairo", country: "Egypt"};
let obj3 = {title: "Engineer", salary: 100000};
let obj4 = {brand: "Honda", model: "Civic"};
let obj5 = {subject: "Science", grade: "B"};

console.log(str1);
console.log(str2);
console.log(str3);
console.log(str4);
console.log(str5);
console.log(str6);
console.log(str7);
console.log(str8);
console.log(str9);
console.log(str10);
console.log(num1);
console.log(num2);
console.log(num3);
console.log(num4);
console.log(num5);
console.log(num6);
console.log(num7);
console.log(num8);
console.log(num9);
console.log(num10);
console.log(bool1);
console.log(bool2);
console.log(bool3);
console.log(bool4);
console.log(bool5);
console.log(bool6);
console.log(bool7);
console.log(bool8);
console.log(bool9);
console.log(bool10);
console.log(arr1);
console.log(arr2);
console.log(arr3);
console.log(arr4);
console.log(arr5);
console.log(obj1);
console.log(obj2);
console.log(obj3);
console.log(obj4);
console.log(obj5);
